USE FLOWER_SHOP;
CREATE OR REPLACE VIEW PURCHASE_DETAILS_AMOUNT_VIEW AS
select FLOWER_SHOP.PURCHASE_DETAILS.`產品編號`, SUM(FLOWER_SHOP.PURCHASE_DETAILS.`採購數量`) as `採購數量`
from FLOWER_SHOP.PURCHASE_DETAILS
group by `產品編號`;
select * from PURCHASE_DETAILS_AMOUNT_VIEW;
CREATE OR REPLACE VIEW ORDERS_DETAILS_AMOUNT_VIEW AS
select FLOWER_SHOP.ORDERS_DETAILS.`產品編號`, SUM(FLOWER_SHOP.ORDERS_DETAILS.`訂購數量`)  as `訂購數量`
from FLOWER_SHOP.ORDERS_DETAILS
group by `產品編號`;
select * from ORDERS_DETAILS_AMOUNT_VIEW;
#進銷存View
CREATE OR REPLACE VIEW STOCK_VIEW AS 
select FLOWER_SHOP.purchase_details_amount_view.`產品編號`, 
		FLOWER_SHOP.PRODUCT.`產品名稱`,
        FLOWER_SHOP.purchase_details_amount_view.`採購數量` as `進貨`,
        FLOWER_SHOP.orders_details_amount_view.`訂購數量` as `銷貨`,
        (FLOWER_SHOP.purchase_details_amount_view.`採購數量` - FLOWER_SHOP.orders_details_amount_view.`訂購數量`) as `庫存`
from FLOWER_SHOP.purchase_details_amount_view,
     FLOWER_SHOP.orders_details_amount_view,
     FLOWER_SHOP.PRODUCT
where FLOWER_SHOP.purchase_details_amount_view.`產品編號` = FLOWER_SHOP.orders_details_amount_view.`產品編號` and
FLOWER_SHOP.PRODUCT.`產品編號`=FLOWER_SHOP.orders_details_amount_view.`產品編號`;
select * from STOCK_VIEW;
#----------------------分割線----------------------
#計算進貨成本View
USE FLOWER_SHOP;
CREATE OR REPLACE VIEW PRODUCT_COST_VIEW AS
select FLOWER_SHOP.PURCHASE_DETAILS_AMOUNT_VIEW.`產品編號`,FLOWER_SHOP.PRODUCT.`產品名稱`,FLOWER_SHOP.PURCHASE_DETAILS_AMOUNT_VIEW.`採購數量`*FLOWER_SHOP.PRODUCT.`成本` as `進貨成本`
from FLOWER_SHOP.PRODUCT,FLOWER_SHOP.PURCHASE_DETAILS_AMOUNT_VIEW
where FLOWER_SHOP.PRODUCT.`產品編號`=FLOWER_SHOP.PURCHASE_DETAILS_AMOUNT_VIEW.`產品編號`;
select * from PRODUCT_COST_VIEW;
#----------------------分割線----------------------
#計算銷貨金額View
USE FLOWER_SHOP;
CREATE OR REPLACE VIEW PRODUCT_SALE_VIEW AS
select FLOWER_SHOP.ORDERS_DETAILS_AMOUNT_VIEW.`產品編號`,FLOWER_SHOP.PRODUCT.`產品名稱`,FLOWER_SHOP.ORDERS_DETAILS_AMOUNT_VIEW.`訂購數量`*FLOWER_SHOP.PRODUCT.`定價` as `銷貨金額`
from FLOWER_SHOP.PRODUCT,FLOWER_SHOP.ORDERS_DETAILS_AMOUNT_VIEW
where FLOWER_SHOP.PRODUCT.`產品編號`=FLOWER_SHOP.ORDERS_DETAILS_AMOUNT_VIEW.`產品編號`;
select * from PRODUCT_SALE_VIEW;
#----------------------分割線----------------------
#計算利潤View
USE FLOWER_SHOP;
CREATE OR REPLACE VIEW PRODUCT_PROFIT_VIEW AS
select FLOWER_SHOP.PRODUCT.`產品編號`,FLOWER_SHOP.PRODUCT.`產品名稱`,SUM((FLOWER_SHOP.PRODUCT.`定價`-FLOWER_SHOP.PRODUCT.`成本`)* FLOWER_SHOP.ORDERS_DETAILS.`訂購數量`)as `利潤`
from FLOWER_SHOP.PRODUCT,FLOWER_SHOP.ORDERS_DETAILS
where FLOWER_SHOP.PRODUCT.`產品編號`=FLOWER_SHOP.ORDERS_DETAILS.`產品編號`
group by `產品編號`,`產品名稱`
order by `產品編號`;
select * from PRODUCT_PROFIT_VIEW;
#----------------------分割線----------------------
#查詢客戶訂單View
USE FLOWER_SHOP;
CREATE OR REPLACE VIEW CLIENT_ORDERS_VIEW AS
select FLOWER_SHOP.CLIENTS.`客戶編號`,FLOWER_SHOP.CLIENTS.`客戶姓名`,FLOWER_SHOP.ORDERS.`訂單編號`,FLOWER_SHOP.ORDERS.`訂單日期`,FLOWER_SHOP.ORDERS.`付款與否`,FLOWER_SHOP.ORDERS.`出貨與否`
from FLOWER_SHOP.CLIENTS,FLOWER_SHOP.ORDERS
where FLOWER_SHOP.CLIENTS.`客戶編號`=FLOWER_SHOP.ORDERS.`客戶編號`;
select * from CLIENT_ORDERS_VIEW;
#----------------------分割線----------------------
#熱銷排行榜View
USE FLOWER_SHOP;
CREATE OR REPLACE VIEW ORDERS_RANK_VIEW AS
select rank() over(ORDER BY `訂購數量` desc) as `排行`,FLOWER_SHOP.ORDERS_DETAILS_AMOUNT_VIEW.`產品編號`,FLOWER_SHOP.PRODUCT.`產品名稱`,FLOWER_SHOP.ORDERS_DETAILS_AMOUNT_VIEW.`訂購數量`
from FLOWER_SHOP.ORDERS_DETAILS_AMOUNT_VIEW,FLOWER_SHOP.PRODUCT
where FLOWER_SHOP.ORDERS_DETAILS_AMOUNT_VIEW.`產品編號`=FLOWER_SHOP.PRODUCT.`產品編號`;
select * from ORDERS_RANK_VIEW;
#----------------------分割線----------------------
#客戶消費排行榜View
USE FLOWER_SHOP;
CREATE OR REPLACE VIEW CLIENT_RANK_VIEW AS
select rank() over(ORDER BY SUM(FLOWER_SHOP.ORDERS_DETAILS.`訂購數量`*FLOWER_SHOP.PRODUCT.`定價`) desc) as `排行`,
FLOWER_SHOP.ORDERS.`客戶編號`,FLOWER_SHOP.CLIENTS.`客戶姓名`,SUM(FLOWER_SHOP.ORDERS_DETAILS.`訂購數量`*FLOWER_SHOP.PRODUCT.`定價`) as `消費總額`
from FLOWER_SHOP.ORDERS_DETAILS,FLOWER_SHOP.PRODUCT,FLOWER_SHOP.ORDERS,FLOWER_SHOP.CLIENTS
where FLOWER_SHOP.ORDERS_DETAILS.`產品編號`=FLOWER_SHOP.PRODUCT.`產品編號` and FLOWER_SHOP.ORDERS.`訂單編號`=FLOWER_SHOP.ORDERS_DETAILS.`訂單編號` and FLOWER_SHOP.CLIENTS.`客戶編號`=FLOWER_SHOP.ORDERS.`客戶編號`
group by `客戶編號`;
select * from CLIENT_RANK_VIEW;
#----------------------分割線----------------------
#銷售員業績排行榜View
USE FLOWER_SHOP;
CREATE OR REPLACE VIEW STAFF_RANK_VIEW AS
select rank() over(ORDER BY SUM(FLOWER_SHOP.ORDERS_DETAILS.`訂購數量`*FLOWER_SHOP.PRODUCT.`定價`) desc) as `排行`,
FLOWER_SHOP.STAFF.`員工編號`,FLOWER_SHOP.STAFF.`員工姓名`,SUM(FLOWER_SHOP.ORDERS_DETAILS.`訂購數量`*FLOWER_SHOP.PRODUCT.`定價`) as `業績(市價)`
from FLOWER_SHOP.STAFF,FLOWER_SHOP.ORDERS,FLOWER_SHOP.ORDERS_DETAILS,FLOWER_SHOP.PRODUCT
where FLOWER_SHOP.STAFF.`員工編號`=FLOWER_SHOP.ORDERS.`員工編號`and FLOWER_SHOP.ORDERS_DETAILS.`產品編號`=FLOWER_SHOP.PRODUCT.`產品編號` and FLOWER_SHOP.ORDERS.`訂單編號`=FLOWER_SHOP.ORDERS_DETAILS.`訂單編號`
group by `員工編號`,`員工姓名`;
select * from STAFF_RANK_VIEW;
#----------------------分割線----------------------
#採購單明細View 
USE FLOWER_SHOP;
CREATE OR REPLACE VIEW PURCHASE_DETAILS_VIEW AS
select FLOWER_SHOP.PURCHASE_DETAILS.`採購明細編號`,FLOWER_SHOP.PURCHASE_DETAILS.`付款與否`,PRODUCT_COST_VIEW.`進貨成本`
FROM FLOWER_SHOP.PURCHASE_DETAILS,FLOWER_SHOP.PRODUCT_COST_VIEW
where FLOWER_SHOP.PURCHASE_DETAILS.`產品編號`=FLOWER_SHOP.PRODUCT_COST_VIEW.`產品編號`
order by `採購明細編號`;
select * from PURCHASE_DETAILS_VIEW;